//constants/index.js
export const supabaseUrl = "https://ajaktnavkbbgeohbgwxs.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYWt0bmF2a2JiZ2VvaGJnd3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM5MjQ1MzIsImV4cCI6MjAzOTUwMDUzMn0.OZhb3_477ehqQ93wGhRCUjdlJMH4BPZ0eDV9hoVEw8A";
